### PR TITLE
Improve the Test

### PR DESCRIPTION
**Pull request by LordRahl90**
This PR is designed to address the following issues:
* Add lint to the project
* Make the naming more go idiomatic eg `FastOtp` to `FastOTP` as `OTP` is an abbrevation.
* Increase the test coverage
* Separate the test process from the build process
* Make some strings constant, eg The `Type` and the `Status` to prevent users from passing wrong values and protect against typographical errors.
* Add comment on all exported functions.
* Configure/Tune the http client that is being used.
* Create a package wide client, instead of creating new http client per request.

### CODE REVIEW

**Comment by CeoFred** [comment]
I see the good work you're doing.. but
Why did you decide to mock http request instead of testing against an actual server?  @LordRahl90

**Comment by LordRahl90** [comment]
> I see the good work you're doing.. but Why did you decide to mock http request instead of testing against an actual server? @LordRahl90

I'm also using a mocked server actually.

However, to see how the library reacts to some errors, that's why I'm mocking the `httpclient` as well. 😄

**Comment by CeoFred** [comment]
@LordRahl90 epp me fixx ur merge conflicts

**Comment by LordRahl90** [comment]
> @LordRahl90 epp me fixx ur merge conflicts

Done with some minor additions. Eg:
* Unexporting the `APIKey`, so it can't be modified once it's set.
* Making the context on a functional level as the client will be set in a global context.

**Review by CeoFred — APPROVED** [review]

**Pull request merged**
